spring:
  application:
    name: gateway
zuul:
  routes:
    user_manager:
      path: /user_manager/**
    goods:
      path: /goods/**
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 600000
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

