spring:
  application:
    name: gateway
zuul:
  routes:
    user_manager:
      path: /user/**
    goods:
      path: /goods/**
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

