spring:
  datasource:
    username: root
    #password: 123456
    #url: jdbc:mysql://192.168.25.131:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=true
    password: 123456
    url: jdbc:mysql://localhost:3306/bookss?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    # type: com.alibaba.druid.pool.DruidDataSource
    #druid：http://localhost:sell/druid

    #全局空值null不返回
  jackson:
    default-property-inclusion: non_null


mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml