spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.196.113.135:3306/shopuser?characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
    #全局空值null不返回
  jackson:
    default-property-inclusion: non_null


server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml